### ISSUE TITLE
add amp reference for normal version

### ISSUE THREAD

**Issue by opentechiz** [tomoyukikashiro/gatsby-plugin-html2amp#39]
Will this plugin also add amp meta to normal website version (hybrid mode) ?

**Comment by tomoyukikashiro** [comment]
@opentechiz Thanks for your comment!

This plugin won't `modify` original html this will `override original` or `create new one` for AMP page only.

So you need some preparations plz check below!
https://github.com/tomoyukikashiro/html2amp#preparation

**Comment by kowalski7cc** [comment]
I think an option to include an option like "include-headers: true" that would add 
`<link rel="amphtml" href="https://www.example.com/url/to/amp/document.html">` to the header if plugin creates new files and doesn't override existing ones. For canonical link there is already here 'gatsby-plugin-canonical-urls' that generates needed tags in headers.
